Snyk Integration and Settings.py secret enhancement

diff --git a/.github/workflows/ci-cd-pipeline.yml b/.github/workflows/ci-cd-pipeline.yml
--- a/.github/workflows/ci-cd-pipeline.yml
+++ b/.github/workflows/ci-cd-pipeline.yml
@@ -11,6 +11,7 @@ jobs:
     env:
       DJANGO_IMAGE_TAG: mctoosh94/mynotes:backend-${{ github.sha }}
       REACT_IMAGE_TAG: mctoosh94/mynotes:frontend-${{ github.sha }}
+      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
 
     steps:
       - name: Checkout Repository
@@ -44,10 +45,28 @@ jobs:
 
       - name: Run Snyk to check for vulnerabilities
         uses: snyk/actions/python@master
+        continue-on-error: true
         env:
           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
         with:
           command: code test
+          args: --sarif-file-output=snyk.sarif
+      - name: Print the snyk sarif file
+        run : cat snyk.sarif
+      - name: Count total number of vulnerabilities
+        run: |
+          RESULTS_LENGTH=$(jq '.runs[0].results | length' snyk.sarif)
+          echo "RESULTS_LENGTH=$RESULTS_LENGTH" >> $GITHUB_ENV
+          echo $RESULTS_LENGTH
+      
+      - name: Pass_or_Fail_the_job
+        run: |
+          if [ "$RESULTS_LENGTH" != 0 ]; then
+                  echo "Job Failed"
+                  exit 1
+              else
+                  echo "Pass"
+              fi
 
       - name: Login to Docker Hub
         uses: docker/login-action@v1
